In [2]:
import numpy as np

## 1. DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray (n - dimanesional array)
a1 = np.array([1, 2, 3])
a1
# print(a1) # --> o/p [1, 2, 3]

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1. , 2. , 3.3],
               [4. , 5. , 6.5]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3 = np.array([[[ 1, 2, 3], 
                [ 4, 5, 6],
                [ 7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
# shape --> (x, y, z) here z represents row, y represents column , x represents depth

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# if your data is in an ndarray, a data type, all of the things were about to go through
# can be used on that.So that's a very important point to remember, is that the ndarray is 
# a universal data type and it's very very flexible to now to really exemplify 
# numpy by being the backbone of other scientific data packages.



In [18]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [19]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [20]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int32')

In [22]:
ones = np.ones((2,3))  # np.ones(|) --> check details at | with shift + tab

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2,3))   # # np.zeros(|) --> check details at | with shift + tab

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0, 10, 2)  # np.arange(|) --> check details at | with shift + tab
range_array

array([0, 2, 4, 6, 8])

In [29]:
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[6, 7, 4, 4, 3],
       [9, 3, 0, 5, 8],
       [6, 8, 2, 6, 1]])

In [30]:
random_array.size

15

In [31]:
random_array.shape

(3, 5)

In [32]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.72520001, 0.7497071 , 0.01293489],
       [0.71794813, 0.18458716, 0.00616691],
       [0.086042  , 0.23150107, 0.17472216],
       [0.90439272, 0.90047072, 0.41576394],
       [0.40084453, 0.51897868, 0.68711923]])

In [33]:
random_array_2.shape

(5, 3)

In [34]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.59600758, 0.79516303, 0.25287628],
       [0.00468408, 0.33898333, 0.51002978],
       [0.82401803, 0.8250296 , 0.48048622],
       [0.98761588, 0.00660028, 0.27170547],
       [0.72155655, 0.24226071, 0.16393754]])

In [35]:
# Pseudo-random numbers
# for passing arguement in seed(x) there is unique result for every different seed x
np.random.seed(seed = 99999) # for passing arguement there is unique result for every
# different seed
random_array_4 = np.random.randint(10, size = (5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [36]:
random_array_4.shape

(5, 3)

In [37]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [38]:
random_array_5.shape

(5, 3)

In [39]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## 3. Viewing arrays and matrices

In [40]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [41]:
a1

array([1, 2, 3])

In [42]:
a1[0]

1

In [43]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [44]:
a2[0]

array([1. , 2. , 3.3])

In [45]:
a2[1]

array([4. , 5. , 6.5])

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [49]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [50]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [51]:
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

In [52]:
# Get the first 4 numbers of the inner most array
a4[:,:,:,:4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

In [53]:
#Similarly
a4[:,:,:,:1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

## 4. Manipulating and comparing arrays

## Arithmetic