In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [23]:
# NumPy's main datatype is ndarray (n - dimanesional array)
a1 = np.array([1, 2, 3])
a1
# print(a1) # --> o/p [1, 2, 3]

array([1, 2, 3])

In [8]:
type(a1)

numpy.ndarray

In [12]:
a2 = np.array([[1. , 2. , 3.3],
               [4. , 5. , 6.5]])

In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
a3 = np.array([[[ 1, 2, 3], 
                [ 4, 5, 6],
                [ 7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
a1.shape

(3,)

In [17]:
a2.shape

(2, 3)

In [18]:
a3.shape

(2, 3, 3)

In [19]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [24]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [25]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [26]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [27]:
# if your data is in an ndarray, a data type, all of the things were about to go through
# can be used on that.So that's a very important point to remember, is that the ndarray is 
# a universal data type and it's very very flexible to now to really exemplify 
# numpy by being the backbone of other scientific data packages.



In [28]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [29]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [31]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [32]:
sample_array.dtype

dtype('int32')

In [43]:
ones = np.ones((2,3))  # np.ones(|) --> check details at | with shift + tab

In [44]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
ones.dtype

dtype('float64')

In [38]:
type(ones)

numpy.ndarray

In [41]:
zeros = np.zeros((2,3))   # # np.zeros(|) --> check details at | with shift + tab

In [42]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
range_array = np.arange(0, 10, 2)  # np.arange(|) --> check details at | with shift + tab
range_array

array([0, 2, 4, 6, 8])

In [48]:
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[3, 5, 0, 7, 7],
       [8, 8, 0, 9, 2],
       [5, 5, 3, 0, 7]])

In [49]:
random_array.size

15

In [50]:
random_array.shape

(3, 5)

In [51]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.1660167 , 0.84879098, 0.77478709],
       [0.11869481, 0.19852475, 0.94433164],
       [0.95715377, 0.35926862, 0.69720976],
       [0.49312775, 0.1210155 , 0.2497781 ],
       [0.17699866, 0.9074693 , 0.98634164]])

In [52]:
random_array_2.shape

(5, 3)

In [56]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.28415784, 0.86016474, 0.26076009],
       [0.36213571, 0.26515554, 0.79763431],
       [0.60934304, 0.91482895, 0.28229194],
       [0.54795452, 0.0631385 , 0.55376918],
       [0.46192841, 0.55043995, 0.61819819]])

In [60]:
# Pseudo-random numbers
np.random.seed()